### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by hohl** [aconbere/Scala-IRC#1]
Would you please define a license for this project? I really like what you've done here.

**Comment by aconbere** [comment]
Yep, it'll take me a day or two to get the commit in. But in the interim
you're welcome to consider the project MIT licensed.

**Comment by hohl** [comment]
Thank you for doing so and a special thank you for reacting so fast.

**Comment by aconbere** [comment]
https://github.com/aconbere/Scala-IRC/blob/master/LICENSE

TADA!

**Comment by hohl** [comment]
Thank you!
